[package]
name = "ray-tracing-in-rust"
version = "0.1.0"
authors = ["Tingjun Li <BrianLTJ@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
